In [1]:
import numpy as np

In [2]:
def obj(x, none_variable):
    simga_y = x[0]
    w = x[1]
    m = x[2]
    return simga_y * w - m

def grad_obj(x, none_variable):
    sigma_y = x[0]
    w = x[1]
    m = x[2]
    grad_g = [w, sigma_y, -1]
    return grad_g

def deterministic_algorithm_structural_analysis(setup: dict):
    mu = [40., 50., 1000.]
    sigma = [5., 2.5, 200.]
    y_0 = [0, 0, 0]
    tol = 1e-6
    n_iter = 20
    jacobian_xy = np.diag(sigma)
    jacobian_xy_trans = np.transpose(jacobian_xy)
    y = y_0.copy() 
    x_y = np.dot(jacobian_xy, y) + mu
    y = np.transpose(np.array([y_0]))
    beta_list = [10000]
    error = 1000
    iter = 0
    print(y, x_y)
    while (error > tol and iter < n_iter):
        beta = np.linalg.norm(y)
        beta_list.append(beta)
        g_y = obj(x_y.flatten().tolist(), None)
        grad_g_x = grad_obj(x_y.flatten().tolist(), None)
        grad_g_y = np.dot(jacobian_xy_trans, np.transpose(np.array([grad_g_x])))
        norm = np.linalg.norm(grad_g_y)
        alpha = grad_g_y / norm
        aux = g_y / norm
        y = -alpha * (beta + aux)
        x_y = np.dot(jacobian_xy, y) + mu
        error = np.abs(beta_list[iter + 1] - beta_list[iter])
        iter += 1
        print(y.T, beta, g_y, norm)
    return beta

In [3]:
# Dataset
f = {'type': 'normal', 'parameters': {'mean': 40, 'sigma': 5.}, 'stochastic variable': False}
p = {'type': 'normal', 'parameters': {'mean': 50, 'sigma': 2.5}, 'stochastic variable': False}
w = {'type': 'normal', 'parameters': {'mean': 1000, 'sigma': 200}, 'stochastic variable': False}
var = [f, p, w]

# PAREpy setup
setup = {
                'tolerance': 1e-6, 
                'max iterations': 20,
                'numerical model': 'fosm', 
                'variables settings': var, 
                'number of state limit functions or constraints': 1, 
                'none variable': None,
                'objective function': obj,
                'gradient objective function': grad_obj,
                'name simulation': None,
        }

# Call algorithm
beta = deterministic_algorithm_structural_analysis(setup)
print(beta)

[[0]
 [0]
 [0]] [  40.   50. 1000.]
[[-2.22222222 -0.88888889  1.77777778]] 0.0 1000.0 335.4101966249685
[[-2.32710189 -0.86435213  2.39359051]] 2.9814239699997196 134.5679012345679 288.1400551086653
[[-2.54652226 -0.94137581  2.65508257]] 3.448446512852427 99.82473961301412 286.0493933263796
[[-2.57956933 -0.94369531  2.76871487]] 3.7974237941959847 28.916986023207528 281.7239732353347
[[-2.61734406 -0.95595071  2.82177051]] 3.90006676664566 18.44609609968063 281.07834592429424
[[-2.62622576 -0.95738375  2.84583302]] 3.965692939444645 6.544142950837113 280.3422629690427
[[-2.63350496 -0.9596077   2.85715822]] 3.9890363443295507 3.756081044978714 280.16948996997564
[[-2.63569654 -0.96005307  2.86236158]] 4.002442804274141 1.474002245904785 280.0279745319907
[[-2.63716259 -0.96048055  2.864806  ]] 4.007706572111509 0.7874447644062457 279.98538275066807
[[-2.63767695 -0.96059656  2.8659353 ]] 4.010519021663946 0.32831041591123267 279.95689510535976
[[-2.63797964 -0.96068177  2.86646443]]