In [1]:
import sys
path = r'C:\Users\wande\OneDrive\Documentos\GitHub\PAREPY'

In [2]:
import itertools
import numpy as np
import pandas as pd

def generate_factorial_design(dict):
    combinations = list(itertools.product(*dict.values()))
    df = pd.DataFrame(combinations, columns=dict.keys())

    return df

niveis_usuario = {
    'i (mm)': np.linspace(0, 10, 3),
    'j (mm)': np.linspace(0, 15, 4),
    'k (mm)': [5, 15],
    'l (mm)': np.linspace(0, 20, 5),
}

df = generate_factorial_design(niveis_usuario)
# df = df.drop_duplicates()
df

i (mm)  j (mm)  k (mm)  l (mm)
0       0.0     0.0       5     0.0
1       0.0     0.0       5     5.0
2       0.0     0.0       5    10.0
3       0.0     0.0       5    15.0
4       0.0     0.0       5    20.0
..      ...     ...     ...     ...
115    10.0    15.0      15     0.0
116    10.0    15.0      15     5.0
117    10.0    15.0      15    10.0
118    10.0    15.0      15    15.0
119    10.0    15.0      15    20.0

[120 rows x 4 columns]

In [3]:
niveis_usuario = {
    'var1': [1, 2, 3],          
    'var2': [4, 5, 6],     
    'var3': [7, 8],            
    'var4': [0, 9, 10, 11, 12],
}

df = generate_factorial_design(niveis_usuario)
df = df.drop_duplicates()
df

var1  var2  var3  var4
0      1     4     7     0
1      1     4     7     9
2      1     4     7    10
3      1     4     7    11
4      1     4     7    12
..   ...   ...   ...   ...
85     3     6     8     0
86     3     6     8     9
87     3     6     8    10
88     3     6     8    11
89     3     6     8    12

[90 rows x 4 columns]

In [4]:
from parepy_toolbox import common_library as cl

sample = cl.sampling_uniform_distribution(0, 1, 10, 42)
sample

AttributeError: module 'parepy_toolbox.common_library' has no attribute 'sampling_uniform_distribution'

In [2]:
teste = cl.inverse_normal_sampling(10, 5, 5, 42, "lhs")
teste

[np.float64(-6.771553715133303),
 np.float64(13.705894848045727),
 np.float64(3.213966512444048),
 np.float64(-1.462018779811065),
 np.float64(7.5008909291748775),
 np.float64(1.185324722650822),
 np.float64(7.916104262483229),
 np.float64(8.927517881386754),
 np.float64(4.8737379322844365),
 np.float64(4.086114929881562)]

In [3]:
teste_gumbel_r = cl.inverse_gumbel_r(10, 5, 5, 42, 'mcs')
teste_gumbel_r

[np.float64(4.909467080249004),
 np.float64(-9.924785134026028),
 np.float64(-0.8240322377849205),
 np.float64(1.6632264441363107),
 np.float64(8.096910564187898),
 np.float64(8.097326660627154),
 np.float64(10.2293471197888),
 np.float64(-4.701286151713267),
 np.float64(1.623159115325218),
 np.float64(-0.3180308830208487)]

In [4]:
teste_gumbel_l = cl.inverse_gumbel_l(10, 5, 5, 42, 'mcs')
teste_gumbel_l

[np.float64(4.909467080249004),
 np.float64(-9.924785134026028),
 np.float64(-0.8240322377849205),
 np.float64(1.6632264441363107),
 np.float64(8.096910564187898),
 np.float64(8.097326660627154),
 np.float64(10.2293471197888),
 np.float64(-4.701286151713267),
 np.float64(1.623159115325218),
 np.float64(-0.3180308830208487)]

In [5]:
teste_triangular = cl.triangular_inverse_cdf(10, 2, 3, 4, 42, 'lhs')
teste_triangular

[array([2.35368344]),
 array([2.45810167]),
 array([2.67349923]),
 array([2.82478379]),
 array([2.98427449]),
 array([3.08111105]),
 array([3.17829677]),
 array([3.19447259]),
 array([3.29606211]),
 array([3.36322613])]

In [6]:
teste_uniform_lhs = cl.uniform_lhs(5, 2, 42)
teste_uniform_lhs

array([[0.12509198, 0.9688011 ],
       [0.20985714, 0.18838328],
       [0.45360121, 0.42676477],
       [0.6802683 , 0.279777  ],
       [0.96879627, 0.65838548]])

In [7]:
model = {
    "model sampling": "MCS"
}

variables_setup = [
    {
        "type": "normal",
        "mean": 0,
        "std": 10,
        "seed": 42
    }
]

n_samples = 10
d = 2

samples = cl.sampling_2(n_samples, d, model, variables_setup)

# Exibindo os resultados
print("Amostras geradas:\n", samples)

Amostras geradas:
 [[ 10.50938884  -2.46158363   5.28343864   0.59859725  -8.98105823
   12.20668796 -12.00344286  -5.18207597   9.92210632  -0.84699262]]
