In [1]:
import sys
path = r'C:\Users\wande\OneDrive\Documentos\GitHub\PAREPY'

In [2]:
import itertools
import numpy as np
import pandas as pd
from tabulate import tabulate

def generate_factorial_design(dict):
    combinations = list(itertools.product(*dict.values()))
    df = pd.DataFrame(combinations, columns=dict.keys())

    return df

niveis_usuario = {
    'i (mm)': np.linspace(0, 10, 3),
    'j (mm)': np.linspace(0, 15, 4),
    'k (mm)': [5, 15],
    'l (mm)': np.linspace(0, 20, 5),
}

df = generate_factorial_design(niveis_usuario)
# df = df.drop_duplicates()
print(tabulate(df, headers='keys', tablefmt='psql'))

+-----+----------+----------+----------+----------+
|     |   i (mm) |   j (mm) |   k (mm) |   l (mm) |
|-----+----------+----------+----------+----------|
|   0 |        0 |        0 |        5 |        0 |
|   1 |        0 |        0 |        5 |        5 |
|   2 |        0 |        0 |        5 |       10 |
|   3 |        0 |        0 |        5 |       15 |
|   4 |        0 |        0 |        5 |       20 |
|   5 |        0 |        0 |       15 |        0 |
|   6 |        0 |        0 |       15 |        5 |
|   7 |        0 |        0 |       15 |       10 |
|   8 |        0 |        0 |       15 |       15 |
|   9 |        0 |        0 |       15 |       20 |
|  10 |        0 |        5 |        5 |        0 |
|  11 |        0 |        5 |        5 |        5 |
|  12 |        0 |        5 |        5 |       10 |
|  13 |        0 |        5 |        5 |       15 |
|  14 |        0 |        5 |        5 |       20 |
|  15 |        0 |        5 |       15 |        0 |
|  16 |     

In [8]:
# Input Levels
setup = {
    'i (mm)': np.linspace(0, 10, 3),
    'j (mm)': np.linspace(0, 15, 4),
    'k (mm)': [5, 15],               
    'l (mm)': [0, 9, 10],
}

# Generate Factorial Design
df = generate_factorial_design(setup)

# Print Results
print(tabulate(df, headers='keys', tablefmt='psql'))

+----+----------+----------+----------+----------+
|    |   i (mm) |   j (mm) |   k (mm) |   l (mm) |
|----+----------+----------+----------+----------|
|  0 |        0 |        0 |        5 |        0 |
|  1 |        0 |        0 |        5 |        9 |
|  2 |        0 |        0 |        5 |       10 |
|  3 |        0 |        0 |       15 |        0 |
|  4 |        0 |        0 |       15 |        9 |
|  5 |        0 |        0 |       15 |       10 |
|  6 |        0 |        5 |        5 |        0 |
|  7 |        0 |        5 |        5 |        9 |
|  8 |        0 |        5 |        5 |       10 |
|  9 |        0 |        5 |       15 |        0 |
| 10 |        0 |        5 |       15 |        9 |
| 11 |        0 |        5 |       15 |       10 |
| 12 |        0 |       10 |        5 |        0 |
| 13 |        0 |       10 |        5 |        9 |
| 14 |        0 |       10 |        5 |       10 |
| 15 |        0 |       10 |       15 |        0 |
| 16 |        0 |       10 |   

In [4]:
niveis_usuario = {
    'var1': [1, 2, 3],          
    'var2': [4, 5, 6],     
    'var3': [7, 8],            
    'var4': [0, 9, 10, 11, 12],
}

df = generate_factorial_design(niveis_usuario)
df = df.drop_duplicates()
print(tabulate(df, headers='keys', tablefmt='psql'))

+----+--------+--------+--------+--------+
|    |   var1 |   var2 |   var3 |   var4 |
|----+--------+--------+--------+--------|
|  0 |      1 |      4 |      7 |      0 |
|  1 |      1 |      4 |      7 |      9 |
|  2 |      1 |      4 |      7 |     10 |
|  3 |      1 |      4 |      7 |     11 |
|  4 |      1 |      4 |      7 |     12 |
|  5 |      1 |      4 |      8 |      0 |
|  6 |      1 |      4 |      8 |      9 |
|  7 |      1 |      4 |      8 |     10 |
|  8 |      1 |      4 |      8 |     11 |
|  9 |      1 |      4 |      8 |     12 |
| 10 |      1 |      5 |      7 |      0 |
| 11 |      1 |      5 |      7 |      9 |
| 12 |      1 |      5 |      7 |     10 |
| 13 |      1 |      5 |      7 |     11 |
| 14 |      1 |      5 |      7 |     12 |
| 15 |      1 |      5 |      8 |      0 |
| 16 |      1 |      5 |      8 |      9 |
| 17 |      1 |      5 |      8 |     10 |
| 18 |      1 |      5 |      8 |     11 |
| 19 |      1 |      5 |      8 |     12 |
| 20 |     

In [5]:
from parepy_toolbox import common_library as cl

sample = cl.sampling_uniform_distribution(0, 1, 10, 42)
sample

AttributeError: module 'parepy_toolbox.common_library' has no attribute 'sampling_uniform_distribution'

In [2]:
teste = cl.inverse_normal_sampling(10, 5, 5, 42, "lhs")
teste

[np.float64(-6.771553715133303),
 np.float64(13.705894848045727),
 np.float64(3.213966512444048),
 np.float64(-1.462018779811065),
 np.float64(7.5008909291748775),
 np.float64(1.185324722650822),
 np.float64(7.916104262483229),
 np.float64(8.927517881386754),
 np.float64(4.8737379322844365),
 np.float64(4.086114929881562)]

In [3]:
teste_gumbel_r = cl.inverse_gumbel_r(10, 5, 5, 42, 'mcs')
teste_gumbel_r

[np.float64(4.909467080249004),
 np.float64(-9.924785134026028),
 np.float64(-0.8240322377849205),
 np.float64(1.6632264441363107),
 np.float64(8.096910564187898),
 np.float64(8.097326660627154),
 np.float64(10.2293471197888),
 np.float64(-4.701286151713267),
 np.float64(1.623159115325218),
 np.float64(-0.3180308830208487)]

In [4]:
teste_gumbel_l = cl.inverse_gumbel_l(10, 5, 5, 42, 'mcs')
teste_gumbel_l

[np.float64(4.909467080249004),
 np.float64(-9.924785134026028),
 np.float64(-0.8240322377849205),
 np.float64(1.6632264441363107),
 np.float64(8.096910564187898),
 np.float64(8.097326660627154),
 np.float64(10.2293471197888),
 np.float64(-4.701286151713267),
 np.float64(1.623159115325218),
 np.float64(-0.3180308830208487)]

In [5]:
teste_triangular = cl.triangular_inverse_cdf(10, 2, 3, 4, 42, 'lhs')
teste_triangular

[array([2.35368344]),
 array([2.45810167]),
 array([2.67349923]),
 array([2.82478379]),
 array([2.98427449]),
 array([3.08111105]),
 array([3.17829677]),
 array([3.19447259]),
 array([3.29606211]),
 array([3.36322613])]

In [6]:
teste_uniform_lhs = cl.uniform_lhs(5, 2, 42)
teste_uniform_lhs

array([[0.12509198, 0.9688011 ],
       [0.20985714, 0.18838328],
       [0.45360121, 0.42676477],
       [0.6802683 , 0.279777  ],
       [0.96879627, 0.65838548]])

In [7]:
model = {
    "model sampling": "MCS"
}

variables_setup = [
    {
        "type": "normal",
        "mean": 0,
        "std": 10,
        "seed": 42
    }
]

n_samples = 10
d = 2

samples = cl.sampling_2(n_samples, d, model, variables_setup)

# Exibindo os resultados
print("Amostras geradas:\n", samples)

Amostras geradas:
 [[ 10.50938884  -2.46158363   5.28343864   0.59859725  -8.98105823
   12.20668796 -12.00344286  -5.18207597   9.92210632  -0.84699262]]
